# Uncomment the next line to define a global platform for your project
# platform :ios, '8.0'

target 'Framework_Demo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  pod 'CocoaLumberjack'
  target 'Framework_DemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
